import './loaders/discord.ts';
import './loaders/electron.ts';
import './loaders/hoyo.ts';
import './loaders/loading.ts';
import './loaders/lrc.ts';
import './loaders/music.ts';
import './loaders/settings.ts';
import './loaders/snapshot.ts';
import './loaders/spotify.ts';
import './loaders/versions.ts';
import './loaders/msx.ts';
import './loaders/dev.ts';
// In preload/index.ts
export type { ElectronAPI } from './loaders/electron.ts';
export type { DiscordAPI } from './loaders/discord.ts';
export type { SpotifyAPI } from './loaders/spotify.ts';
export type { MusicRPCAPI } from './loaders/music.ts';
export type { SettingsAPI } from './loaders/settings.ts';
export type { LoadingAPI } from './loaders/loading.ts';
export type { LrcAPI } from './loaders/lrc.ts';
export type { HoyoAPI } from './loaders/hoyo.ts';
export type { SnapshotAPI } from './loaders/snapshot.ts';
export type { MsxAPI } from './loaders/msx.ts';
export type { DevAPI } from './loaders/dev.ts';
