name: Build
on: workflow_dispatch

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Change to project directory (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd Iris
          pwd
          dir

      - name: Change to project directory (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd Iris
          pwd
          ls -la

      - name: Install dependencies
        working-directory: Iris
        run: |
          cd Iris
          npm install

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        working-directory: Iris
        run: npm run build:win

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        working-directory: Iris
        run: npm run build:mac

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: Iris
        run: npm run build:linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            out/make/**/*.exe
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.dmg
