name: Build
on: workflow_dispatch

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Change to project directory (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd Iris
          pwd
          dir

      - name: Change to project directory (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd Iris
          pwd
          ls -la

      - name: Install dependencies
        working-directory: Iris
        run: |
          npm install
          npm install --save-dev @electron-forge/cli
          npm install --save-dev @electron-forge/maker-deb @electron-forge/maker-rpm
          npx electron-forge import

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        working-directory: Iris
        run: npx electron-forge make --platform win32

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        working-directory: Iris
        run: npx electron-forge make --platform darwin

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: Iris
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm elfutils
          sudo add-apt-repository ppa:flatpak/stable
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          npx electron-forge make --platform linux --targets=@electron-forge/maker-deb,@electron-forge/maker-rpm

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            Iris/out/make/**/*.exe
            Iris/out/make/**/*.deb
            Iris/out/make/**/*.rpm
            Iris/out/make/**/*.dmg
